import type { DocSectionId } from "./types";
import {
  AlertCircleIcon,
  Analytics01Icon,
  BookOpen02Icon,
  BubbleChatIcon,
  Call02Icon,
  DashboardCircleIcon,
  File02Icon,
  Folder02Icon,
  GridViewIcon,
  HelpCircleIcon,
  KeyboardIcon,
  Login01Icon,
  MapsIcon,
  Notification01Icon,
  Rocket01Icon,
  Search01Icon,
  Settings01Icon,
  SmartPhone01Icon,
  Task01Icon,
  UserAdd01Icon,
  UserCircleIcon,
  UserGroupIcon,
} from "@hugeicons/core-free-icons";

export const DOC_SECTION_ICONS: Record<DocSectionId, typeof BookOpen02Icon> = {
  "getting-started": Rocket01Icon,
  auth: Login01Icon,
  navigation: MapsIcon,
  workspace: UserGroupIcon,
  invites: UserAdd01Icon,
  dashboard: DashboardCircleIcon,
  projects: Folder02Icon,
  "board-views": GridViewIcon,
  tasks: Task01Icon,
  chats: BubbleChatIcon,
  meetings: Call02Icon,
  documents: File02Icon,
  search: Search01Icon,
  notifications: Notification01Icon,
  profile: UserCircleIcon,
  settings: Settings01Icon,
  analytics: Analytics01Icon,
  "web-vs-mobile": SmartPhone01Icon,
  "mobile-app": SmartPhone01Icon,
  faq: HelpCircleIcon,
  "keyboard-shortcuts": KeyboardIcon,
  troubleshooting: AlertCircleIcon,
  "docs-guide": BookOpen02Icon,
};
